### ISSUE TITLE
Raft-WSL does not support Pengwin Enterprise 8

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#14]
It is not a big issue, anyway Pengwin Enterprise 8 is present in Raft-WSL but you cannot update from there, also the icon is strange!!! (Maybe it is supposed to be like it).

![BugRaft](https://user-images.githubusercontent.com/64733228/137903737-1200f898-3cc9-42ee-905d-a2adcecbf48a.PNG)

 Pengwin Enterprise 8 not present in available distributions as should be. 

![BugRaft](https://user-images.githubusercontent.com/64733228/137906722-cb0fd6e0-f394-43db-bc9c-59b55b261a51.PNG)

**Comment by crramirez** [comment]
Hello @Jack31071973 ,

Thanks for reporting. We will try to solve this as soon as possible.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

There is a new release in the store with the fix. Check it out.

Regards,
Carlos

**Comment by Jack31071973** [comment]
it is working fine now.

**Comment by Jack31071973** [comment]
This behavior works as expected.
