### ISSUE TITLE
Just a naming typo.

### ISSUE THREAD

**Issue by akulbe** [WhitewaterFoundry/Raft-WSL-Feedback#18]
![image](https://user-images.githubusercontent.com/123279/138742769-61fd15da-17af-4995-9592-10151c182444.png)

**Comment by akulbe** [comment]
Thank you for your work on this, Carlos!

**Comment by crramirez** [comment]
Thank you for reporting. We will fix it soon and include it in the next release.

**Comment by crramirez** [comment]
@akulbe we released a new beta with the fix and other minor fixes and adjustments  to the UI
