### ISSUE TITLE
would be nice if name of distro could be changed and reflected in raft... once done it i lost to raft...

### ISSUE THREAD

**Issue by BobRusch** [WhitewaterFoundry/Raft-WSL-Feedback#2]
did a dist upgrade from 20.04 to 20.10 so update Registry... Oops... broken link now.. Raft can't find distro.. this is not just a raft issue, but Microsoft issue too, the app also doesn't launch either. It would be nice to be able to change names to reflect current OS releases..... THANKS

**Comment by crramirez** [comment]
Hello,

I don't understand what you did and what Raft should do. I only have a vague idea. Could you please post the result of `wsl.exe --list --verbose` ? I understand that you changed the distribution name on registry?

Please explain step by step so we can reproduce it

Regards,
Carlos

**Comment by crramirez** [comment]
After reading again the title, I understand. This issue will be solved at least partially with the upcoming custom distro support in Raft. If you wish to participate in the beta just write to me: contact@whitewaterfoundry.com

**Comment by BobRusch** [comment]
Sorry that I didn't respond sooner, but been very busy.

Yes, I would like to be aboard to test the beta version. Working with
multiple versions of distros at the moment and like raft as the management
platform.

Thanks,
Bob

**Comment by crramirez** [comment]
Hello,

Because it is not a public beta I need you write to me at contact@whitewaterfoundry.com so I can send you a code to activate the feature. Beware the feature is not final and some things are not working like the Update menu option.

Regards

**Comment by crramirez** [comment]
Here is the Raft roadmap: https://www.whitewaterfoundry.com/blog/2019/12/15/raft-roadmap-2020

**Comment by crramirez** [comment]
This feature is planned after the graphics applications, but due to the high demand, we will release a basic version before that. And we will improve it over time

**Comment by crramirez** [comment]
Hello @BobRusch 

We have a beta version with this functionality added included the rename feature. Stay tuned we will release it at the end of January / Beginning of February.

![image](https://user-images.githubusercontent.com/8397379/105179321-7e8eb300-5b29-11eb-8347-bd2d99803a6a.png)

Regards,
Carlos
