### ISSUE TITLE
Snapshot doesn't work correctly

### ISSUE THREAD

**Issue by skybarberom** [WhitewaterFoundry/Raft-WSL-Feedback#20]
I am trying to perform a snapshot. After I set the name, it run for a while and it says: couldn't create the backup: The operation completed succesfully

![image](https://user-images.githubusercontent.com/87366420/141813971-16fcc44d-8110-4124-b134-c6afa02f57fe.png)

![image](https://user-images.githubusercontent.com/87366420/141814106-1b1a432b-e0d8-4cd3-aa2f-e74a20366724.png)

In the snapshot tab I see only my first snapshot made 1 month ago.

![image](https://user-images.githubusercontent.com/87366420/141814723-dc37b835-74af-4c36-9426-3d516c2cfa1e.png)

On the filesystem I see all the snapshot taken:

![image](https://user-images.githubusercontent.com/87366420/141814487-196823ae-7b45-48cb-97e0-9d8b7b31e2eb.png)

backup_database.yaml  file is not updated.

Am I doing something wrong?

**Comment by crramirez** [comment]
Hello,

Thank you for reporting. Do you have WSL Preview - Microsoft Store Edition? Today we released a fix that corrects exactly the error that you are facing. It is a compatibility issue with this WSL version.

Please check if you have Raft 21.11.6 and try again. If you still face this issue please tell me. 

Regards,
Carlos

**Comment by skybarberom** [comment]
Yes I installed the WSL from MS Store. I confirm now it's working (Raft was updated in the last couple of hours automatically). Thank you

**Comment by crramirez** [comment]
We are still improving the compatibility with this WSL version. So, if you find anything wrong don't hesitate to report it.

Regards,
Carlos
