### ISSUE TITLE
Set default Distro does not work as expected.

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#22]
Step to reproduce:
- choose default distros from "distribution page" (set Pengwin, please see attached file).
![SyncDist_DoesNotWork](https://user-images.githubusercontent.com/64733228/145023691-e91fdd7f-935c-480b-84b3-c97906c6a183.PNG)

- Go to Setting Page and check the default distros, in my case should be Pengwin bat it is Ubuntu 20.04 (Please find attached image).
![ChangedDefaultDistros](https://user-images.githubusercontent.com/64733228/145024215-7a8bb0b1-ffae-4b6a-b3da-7b06ac12e700.PNG)

Default distros is changed again from Pengwin (as I set) to Ubuntu 20.04. It is not a big issue, because I can choose my distros from the ide and set there.

**Comment by crramirez** [comment]
Hello @Jack31071973,

Thanks a lot for reporting. A new version 21.12.1 is on the way, with this fix included and also some optimizations so it won't try to repeatedly change the default distribution.

Regards,
Carlos

**Comment by Jack31071973** [comment]
The update is installed, I tried it, and everything is working fine now.
