### ISSUE TITLE
Add ability to register or import custom distributions

### ISSUE THREAD

**Issue by justinbarclay** [WhitewaterFoundry/Raft-WSL-Feedback#23]
I manage my own custom Arch distro and when repaving my OS or when moving my distro to another hard drive I run into issues.
For example, today I was testing out your software to see if it supported my use case (because lxrunoffline broke recently), where I needed to register my custom distro with WSL. Unfortunately, that did not work, so I had to learn how to register it myself by updating the registry.

Also, I often enough try out docker images with uncommon distributions on them (Guix or Gentoo for example) and I would like it if WSL-Raft allowed me to import docker images or containers as new custom distributions.

**Comment by crramirez** [comment]
Hello @justinbarclay ,

Thank you for the feedback, this feature is in our roadmap but thanks to your request we will raise its priority and have it soon.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello @justinbarclay,

Your requested feature is now in beta. Would you like to join the beta program? Or just wait by the end of the month for the release. We are still working on the Arch implementation because it needs additional steps. 

Regards,
Carlos

**Comment by WSLUser** [comment]
I can test this but look like the beta subscriptions have expiration dates. If there's a way to renew it, I can provide feedback this weekend. This has been one of my most desired features from Raft so I'd give it a whirl for several distros. I'd be testing:

Clear Linux
Custom Ubuntu exported from `wsl -export`
Alma Linux (might need to export this one too as I believe they have a custom appx for wsl).
I'd be willing to switch one of those options out for Gentoo but I think it's related to Arch in some way if I recall so not sure how well that one would work. 

If there's a particular distro in mind for testing I haven't listed let me know.

**Comment by crramirez** [comment]
Hello @WSLUser 

Any distro can be imported but with only the following Raft will be able to configure a default user:

- Debian, Ubuntu, Kali
- RHEL, Oracle Linux
- Gentoo
- Arch

We will add more with time, and also add generic support based on the ID_LIKE property.

Clear and Alma will be added soon

**Comment by crramirez** [comment]
The version 22.7.4 to be released in the store tomorrow will include this feature

![image](https://user-images.githubusercontent.com/8397379/180776773-419cad63-6ebe-451c-84ee-43c161cf8082.png)
