### ISSUE TITLE
Trivial bug: Name of installed distro are written in normal text or bold text.

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#24]
All distros are not running but the names have different text format: normal or bold.
Please find attache image. The names of distros should be in normal text in this case.

![WSLRaftError](https://user-images.githubusercontent.com/64733228/149465297-3035e079-f4e6-4f59-aa95-f35210a29d4c.png)

Anyway, this is a trivial bug (applied to Windows 11 and 10).

Edition	Windows 11 Pro for Workstations
Version	21H2
Installed on	‎1/‎13/‎2022
OS build	22000.434
Experience	Windows Feature Experience Pack 1000.22000.434.0

Raft-WSL: 21.12.1.0

**Comment by crramirez** [comment]
Hello @Jack31071973,

The distro names become bold when they are running. Check with the following command if the distros are indeed not running.

`wsl --list --verbose`

Regards,
Carlos

**Comment by Jack31071973** [comment]
Yes, you are right, but I do not why they are still running.

PS C:\Users\gTrim> wsl --list --verbose
  NAME                  STATE           VERSION
* WLinux                Running             2
  Debian                 Stopped             2
  fedoraremix         Stopped             2
  PengwinEnterprise8    Running     2
  WLE                   Stopped              2
  Alpine                Stopped              2
  Ubuntu-20.04          Running        2
PS C:\Users\gTrim>

Stop WSL from Raft-WSL (shotdown wsl button) works all process are stopped.
