### ISSUE TITLE
Please allow default terminal to be opened, rather than only stable version.

### ISSUE THREAD

**Issue by akulbe** [WhitewaterFoundry/Raft-WSL-Feedback#26]
![Raft_Enhancement Request](https://user-images.githubusercontent.com/123279/152560451-087eb7da-6e66-4232-9f1f-dcb0227fa1a3.png)

**Comment by crramirez** [comment]
Hello @akulbe,

The terminal that Raft uses depends on which version is the wt.exe alias is pointing to. To change it go to Apps & Features in Settings: ms-settings:appsfeatures choose More Settings and App executions aliases. Then enable the version that you want to be launched by default when the wt.exe command is invoked:

![image](https://user-images.githubusercontent.com/8397379/154128902-80f8ae42-97c5-4305-81fc-97d697d59f5a.png)

Best Regards,
Carlos
