### ISSUE TITLE
Raft -WSL show in "Available Distributions" distro already installed

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#29]
Raft -WSL show in "Available Distributions" distro already installed. Please see attached image.
![Bug_WSL](https://user-images.githubusercontent.com/64733228/162496982-7dfca764-183a-46d2-aef1-425af72d0630.png)

Oracle 7.9 is Oracle Linux.

**Comment by crramirez** [comment]
Hello @Jack31071973,

Thank you for reporting. When Oracle Linux was released to the Store, they released 2 versions with the same distro name without the version number. We released a version of Raft supporting it. About 2 weeks later they rectified and released an update with the version numbers in the distribution names. Then we released a new version. 

I figure that you installed Oracle Linux before the fix, and this is why you see still Oracle Linux 7.9 still available. If you wish do a `wsl --list --verbose` you should have OracleLinux and OracleLinux_8_5 but no OracleLinux_7_9

Regards

**Comment by Jack31071973** [comment]
Yes, correct I installed Oracle Linux before the fix.
