### ISSUE TITLE
Please add feature to allow Raft to take snapshots of non-standard distros

### ISSUE THREAD

**Issue by akulbe** [WhitewaterFoundry/Raft-WSL-Feedback#3]
I made a "custom" distro (which was just an export of Ubuntu-18.04) and renamed it and put the company logo on it. I put my company-specific configuration in this distro and wanted to take a snapshot of it with Raft, but it doesn't show up, because it's not one of the ones that are in the Microsoft Store.

**Comment by crramirez** [comment]
Hello @akulbe,

This is a feature currently under development. I can send you a code to activate the preview feature if you write to me at contact@whitewaterfoundry.com 

Regards,
Carlos

**Comment by crramirez** [comment]
This feature is planned after the graphics applications, but due to the high demand, we will release a basic version before that. And we will improve it over the time

**Comment by crramirez** [comment]
Here is the Raft roadmap: https://www.whitewaterfoundry.com/blog/2019/12/15/raft-roadmap-2020

**Comment by crramirez** [comment]
Hello,

Your requested feature is now in beta. We expect to release it at the end of January or the beginning of February. 

![image](https://user-images.githubusercontent.com/8397379/105179545-c1508b00-5b29-11eb-9a65-6e5743a344e6.png)

Regards,
Carlos
