### ISSUE TITLE
PowerToys is not working in combination with Raft WSL

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#31]
This is an old bug I should re-open because my solutions do not work anymore.

This is the steps we used to fix the problem:
https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/issues/13

Edition	Windows 11 Pro for Workstations
Version	22H2
Installed on	‎9/‎21/‎2022
OS build	22621.755
Serial number	PF1ZJVZL
Experience	Windows Feature Experience Pack 1000.22636.1000.0

PowerToys Version: V 0.64.0 (The latest). There is no option to enable raft-WSL in PowerToys

From where I should copy the file and where I should paste it? Can you write down the folder Path?

Here where I copied!!!

![2022-11-03 (2)](https://user-images.githubusercontent.com/64733228/199668698-8c28af16-53f7-4223-8835-ea7dca5c814d.png)

Here is the result where in PowerToys there is no button to enable it:

![2022-11-03 (1)](https://user-images.githubusercontent.com/64733228/199669122-0299138b-dacd-44ad-9233-b364bd3df9b7.png)

**Comment by crramirez** [comment]
Hello @Jack31071973,

I'll check if something with the new PowerToys version is not working. In either case, I'll update the issue with the list of files that needs to be copied, not only the DLL is needed.

Regards,
Carlos

**Comment by Jack31071973** [comment]
Ok, Thanks, I will wait for the list. No silent message is displayed as you wrote in the old bugs, bur can be my configuration (I do not know why anyway).

**Comment by Jack31071973** [comment]
Do we have any news here? May you post the list of files?
It does not work with version 0.64.1 as well. The rest is working perfectly.

**Comment by crramirez** [comment]
I tested it, and it is working with version 0.64.1. So, you only need the file list. I'll post it here later today.

Thanks for your patience.

**Comment by crramirez** [comment]
![image](https://user-images.githubusercontent.com/8397379/200804894-7d388d1c-a979-4bef-9c9a-05965ba5c4d0.png)
Check if it works with these files

**Comment by crramirez** [comment]
Copy the files to `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\WhitewaterFoundry.Plugin.RaftWSL`

**Comment by crramirez** [comment]
https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/issues/13#issuecomment-985724977

**Comment by Jack31071973** [comment]
Ok, I have fixed it, and now it is working. I noticed this thing:
- If you try to copy the files into %LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\WhitewaterFoundry.Plugin.RaftWSL
- the folder \WhitewaterFoundry.Plugin.RaftWSL it is not created so the error because it cannot find the location in my case.
- I just created it and copied the files inside and it is going to work.

**Comment by crramirez** [comment]
@Jack31071973 Finally we found the issue that prevented you and others to have the plug-in automatically installed for Raft.

Also Raft is fully native now and starts faster, also is quicker showing the options in PowerToys run.

Check the version 25.7.2 just released today.
