### ISSUE TITLE
Dark Themes, text color is black

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#35]
It is not big deal (because everything is working at least)

Edition	Windows 11 Pro for Workstations
Version	22H2
Installed on	‎9/‎21/‎2022
OS build	22621.2506
Experience	Windows Feature Experience Pack 1000.22677.1000.0

Raft-WSL version:  23.11.10

Please see the attached image.
You can try to switch themes (from light to dark and viceversa) several times to replicate the issue, but in any case
shut-down Raft and restart solved the problem. 

![raft_WSL dark_thema](https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/assets/64733228/a6140f13-4164-4584-8a45-769538c9ba3a)

**Comment by crramirez** [comment]
Indeed, looks weird. I have experience this at least once. Does this behavior persist among app restarts or theme changes?

On the other hand, we have released a new version of the PowerToys plugin that makes it compatible with PowerToys 0.75 and also gives improvements with the dark theme.

**Comment by Jack31071973** [comment]
No, when you restart everything is working fine. About PowerToys I removed it, it seems i slowed down my system. I also got stuck on WSL when PowerToys was installed, after removed it, all works fine (it was not connected maybe, and I saw similar issue here).

**Comment by Jack31071973** [comment]
Fill free to close the issue.

**Comment by Jack31071973** [comment]
It does not happen anymore
