### ISSUE TITLE
PowerToys Run - Plugin Loading error 

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Raft-WSL-Feedback#39]
Fail to load plugin: Raft WSL (Every time I switch on my laptop)

**PowerToys Version: v0.77.0**

**Edition	Windows 11 Pro for Workstations**
Version	23H2
Installed on	‎9/‎21/‎2022
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Raft WSL version: 23.11.0**

![image](https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/assets/64733228/df7ab91d-a549-43b6-9d2d-1bdc2d31af4d)

**Comment by crramirez** [comment]
They made a change that breaks the integration. There is an updated version of the plugin inside Raft. Just follow again the steps here https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/issues/31

**Comment by Jack31071973** [comment]
Fine, it is working
