### ISSUE TITLE
Raft WSL is crashing Windows Terminal

### ISSUE THREAD

**Issue by tstephansen** [WhitewaterFoundry/Raft-WSL-Feedback#5]
I am unable to use Windows Terminal Preview with Raft WSL installed. I created a bug report on their GitHub and they told me to notify you all that your fragment is breaking terminal.

[https://github.com/microsoft/terminal/issues/9473](https://github.com/microsoft/terminal/issues/9473)

I am able to open and run terminal as soon as Raft is uninstalled and I'm unable to open it when Raft is reinstalled.

**Comment by crramirez** [comment]
Thank you for letting us know. We will release a new version without the fragment for now. If you want send me to contact@whitewaterfoundry.com your Microsoft account email address so you can receive the update faster.

**Comment by tstephansen** [comment]
@crramirez Thanks for the quick response! I just shot an email your way.

**Comment by crramirez** [comment]
The release with the fix is live. Version 21.3.1
